backbones:
  red_fox_backbone1: data/bb_simp1.tsv
  red_fox_backbone2: data/bb_simp2.tsv
  red_fox_backbone3: data/bb_simp3.tsv
  red_fox_backbone4: data/bb_simp4.tsv

master_file_set:
  master_no_ext:  data/Sib_vulpes_pruned_renamed_95_contigs

target_list:
  tl:  data/tar_fox_ref

model_scripts:
  adm_models_to_fit: scripts/adm_graph_Models_simple.R
  adm_graphs: scripts/adm_graph_schematics_simple_bb.R

analysis_name:  rf_simple_backbone

chr_set:  chr-set 95
